// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Gender               string   `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Latitude             float64  `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Religion             string   `protobuf:"bytes,6,opt,name=religion,proto3" json:"religion,omitempty"`
	Nationality          string   `protobuf:"bytes,7,opt,name=nationality,proto3" json:"nationality,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_01adb65ad2f3bab9, []int{0}
}
func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (dst *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(dst, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserRequest) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *UserRequest) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *UserRequest) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *UserRequest) GetReligion() string {
	if m != nil {
		return m.Religion
	}
	return ""
}

func (m *UserRequest) GetNationality() string {
	if m != nil {
		return m.Nationality
	}
	return ""
}

type UserResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_01adb65ad2f3bab9, []int{1}
}
func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (dst *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(dst, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *UserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*UserRequest)(nil), "user.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "user.UserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegisterClient is the client API for Register service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegisterClient interface {
	RegistUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type registerClient struct {
	cc *grpc.ClientConn
}

func NewRegisterClient(cc *grpc.ClientConn) RegisterClient {
	return &registerClient{cc}
}

func (c *registerClient) RegistUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/user.Register/RegistUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterServer is the server API for Register service.
type RegisterServer interface {
	RegistUser(context.Context, *UserRequest) (*UserResponse, error)
}

func RegisterRegisterServer(s *grpc.Server, srv RegisterServer) {
	s.RegisterService(&_Register_serviceDesc, srv)
}

func _Register_RegistUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServer).RegistUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.Register/RegistUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServer).RegistUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Register_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.Register",
	HandlerType: (*RegisterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegistUser",
			Handler:    _Register_RegistUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_01adb65ad2f3bab9) }

var fileDescriptor_user_01adb65ad2f3bab9 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4e, 0xf3, 0x30,
	0x14, 0x84, 0x7f, 0xff, 0x6d, 0xd3, 0xe6, 0x95, 0x05, 0xbc, 0x05, 0xb2, 0x2a, 0x90, 0xa2, 0x6c,
	0xc8, 0x2a, 0x0b, 0x10, 0x3b, 0x36, 0xf4, 0x04, 0xc8, 0x12, 0x07, 0x70, 0x92, 0x27, 0x63, 0x91,
	0xd8, 0xc5, 0x76, 0x90, 0x38, 0x1f, 0x17, 0x43, 0x76, 0x68, 0xc8, 0xee, 0x9b, 0x99, 0xe4, 0x59,
	0x33, 0x00, 0xa3, 0x27, 0x57, 0x9f, 0x9c, 0x0d, 0x16, 0xd7, 0x91, 0xcb, 0x6f, 0x06, 0xfb, 0x57,
	0x4f, 0x4e, 0xd0, 0xc7, 0x48, 0x3e, 0x20, 0xc2, 0xda, 0xc8, 0x81, 0x38, 0x2b, 0x58, 0x95, 0x8b,
	0xc4, 0x78, 0x09, 0x2b, 0xa9, 0x88, 0xff, 0x2f, 0x58, 0xb5, 0x11, 0x11, 0xf1, 0x1a, 0x32, 0x45,
	0xa6, 0x23, 0xc7, 0x57, 0xe9, 0xbb, 0x5f, 0x85, 0x07, 0xd8, 0xf5, 0x32, 0xe8, 0x30, 0x76, 0xc4,
	0xd7, 0x05, 0xab, 0x98, 0x98, 0x35, 0xde, 0x40, 0xde, 0x5b, 0xa3, 0xa6, 0x70, 0x93, 0xc2, 0x3f,
	0x23, 0xfe, 0xe9, 0xa8, 0xd7, 0x4a, 0x5b, 0xc3, 0xb3, 0x74, 0x73, 0xd6, 0x58, 0xc0, 0xde, 0xc8,
	0xa0, 0xad, 0x91, 0xbd, 0x0e, 0x5f, 0x7c, 0x9b, 0xe2, 0xa5, 0x55, 0x3e, 0xc1, 0xc5, 0x54, 0xc2,
	0x9f, 0xac, 0xf1, 0x14, 0x5b, 0xb4, 0xb6, 0x9b, 0x5b, 0x44, 0x46, 0x0e, 0xdb, 0x81, 0xbc, 0x3f,
	0x37, 0xc9, 0xc5, 0x59, 0xde, 0x3f, 0xc3, 0x4e, 0x90, 0xd2, 0x3e, 0x90, 0xc3, 0x47, 0x80, 0x89,
	0xe3, 0x3d, 0xbc, 0xaa, 0xd3, 0x60, 0x8b, 0x81, 0x0e, 0xb8, 0xb4, 0xa6, 0xe7, 0xca, 0x7f, 0xc7,
	0x3b, 0xb8, 0x6d, 0xed, 0x50, 0x2b, 0x1d, 0xde, 0xc6, 0xa6, 0x6e, 0x64, 0xfb, 0x4e, 0xa6, 0xf3,
	0xe4, 0x3e, 0x75, 0x4b, 0x75, 0xa3, 0xd5, 0x31, 0xad, 0xfd, 0xc2, 0x9a, 0x2c, 0x8d, 0xff, 0xf0,
	0x13, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x92, 0xf6, 0xc1, 0x8a, 0x01, 0x00, 0x00,
}
